# Created by trellis-cli v1.13.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  test-woocommerce.lostium.com:
    site_hosts:
    - canonical: test-woocommerce.lostium.test
      redirects: []
    local_path: ../site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: false
    admin_user: lostium
    admin_email: found@lostium.com
