# Created by trellis-cli v1.13.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  test-woocommerce.lostium.com:
    site_hosts:
    - canonical: test-woocommerce.lostium.com
      redirects: []
    local_path: ../site
    branch: main
    repo: git@github.com:lostium/test-woocommerce.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
